spring.datasource.url=jdbc:mysql://localhost:3306/smart_cooling
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=8080
